#!/bin/sh

NVIM_DIR=$HOME/.config/nvim
echo "Setting up neovim in '$NVIM_DIR'"

mkdir -p $NVIM_DIR


# Install neovim
sudo apt install -y software-properties-common
if ! grep -qE "^[^#]+neovim-ppa/unstable" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
	sudo add-apt-repository ppa:neovim-ppa/unstable
else
	echo "ppa:neovim-ppa/unstable already added"
fi
sudo apt update
sudo apt install -y neovim

# Python Modules
sudo apt install -y python-dev python-pip python3-dev python3-pip
sudo pip2 install neovim
sudo pip3 install neovim

# Dependencies
sudo apt install clang libclang-dev golang-go npm tidy
sudo pip3 install vim-vint jedi
sudo npm install -g jshint jsonlint csslint

mkdir -p ~/go
export GOPATH=$HOME/go
go get -u github.com/nsf/gocode
nvim +GoInstallBinaries +qall
